# Generated by Django 5.0.4 on 2024-04-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('d', 'Debit'), ('c', 'Credit')], max_length=1),
        ),
    ]
